// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Repository.Data;

#nullable disable

namespace Pos.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212172701_AddCentralOrderId")]
    partial class AddCentralOrderId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS.Core.Entities.Categorie.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("Invisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemsFont")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("KitchenTypeId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<bool?>("PrintInBackupReceipt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("KitchenTypeId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("POS.Core.Entities.Company.Branch", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("LogoHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<int>("LogoWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Phone1")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Phone2")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("Suspend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("POS.Core.Entities.Company.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("NormalizedEnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("POS.Core.Entities.Customer.TakeawayCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerPhone")
                        .IsUnique();

                    b.ToTable("TakeawayCustomers", (string)null);
                });

            modelBuilder.Entity("POS.Core.Entities.Date.AppDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentOrderNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("PosDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("StoreDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("AppDates", (string)null);
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DeliveryCustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryZoneId")
                        .HasColumnType("int");

                    b.Property<string>("FlatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FloorNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HomeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZoneName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DeliveryCustomerId");

                    b.HasIndex("DeliveryZoneId");

                    b.ToTable("CustomerAddress");
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.DeliveryCompanyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AssignTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BackTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalOrdersAmount")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalOrdersCash")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryCompanyInfo");
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.DeliveryCustomerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstPhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SecondPhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryCustomerInfo");
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.DeliveryCustomerTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryCustomerTitle");
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.DeliveryZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DeliveryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("DeliveryZones", (string)null);
                });

            modelBuilder.Entity("POS.Core.Entities.DineIn.DineInOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CaptainId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CaptainName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CashierId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CashierName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ClosedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNotice")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderState")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Open");

                    b.Property<decimal?>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Cash");

                    b.Property<int>("PrintCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Remain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Service")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderDateTime");

                    b.HasIndex("OrderId");

                    b.HasIndex("TableId");

                    b.HasIndex("TableId", "OrderState");

                    b.ToTable("DineInOrders");
                });

            modelBuilder.Entity("POS.Core.Entities.DineIn.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BoothSeating")
                        .HasColumnType("bit");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LoadIndex")
                        .HasColumnType("int");

                    b.Property<int?>("LocationX")
                        .HasColumnType("int");

                    b.Property<int?>("LocationY")
                        .HasColumnType("int");

                    b.Property<bool?>("NearWindows")
                        .HasColumnType("bit");

                    b.Property<bool?>("PrivateSeating")
                        .HasColumnType("bit");

                    b.Property<int?>("SeatsCount")
                        .HasColumnType("int");

                    b.Property<bool?>("SmokingSection")
                        .HasColumnType("bit");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TableShape")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TableState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Available");

                    b.Property<string>("TimeStamp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Usable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("GroupID");

                    b.ToTable("Tables", (string)null);
                });

            modelBuilder.Entity("POS.Core.Entities.DineIn.TableGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TableGroups", (string)null);
                });

            modelBuilder.Entity("POS.Core.Entities.Item.AttributeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppearanceIndex")
                        .HasColumnType("int");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("RelatedMenuItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("RelatedMenuItemId");

                    b.ToTable("AttributeItems");
                });

            modelBuilder.Entity("POS.Core.Entities.Item.Attributes", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("POS.Core.Entities.Item.MenuSalesItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("AttributeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AttributePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BackColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<decimal?>("FifthPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FourthPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasAttribute")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Invisible")
                        .HasColumnType("bit");

                    b.Property<int?>("KitchenTypeId")
                        .HasColumnType("int");

                    b.Property<string>("MainCategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("PrintInBackupReceipt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("SecondPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TextColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int?>("TextSize")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThirdPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId")
                        .IsUnique()
                        .HasFilter("[AttributeId] IS NOT NULL");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("KitchenTypeId");

                    b.ToTable("MenuSalesItems");
                });

            modelBuilder.Entity("POS.Core.Entities.Item.OrderItemAttributes", b =>
                {
                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int?>("AttributeItemId")
                        .HasColumnType("int");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId", "AttributeItemId");

                    b.HasIndex("AttributeItemId");

                    b.ToTable("OrderItemAttributes");
                });

            modelBuilder.Entity("POS.Core.Entities.Kitchen.KitchenPrinters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Copy1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy10")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy6")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy7")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy8")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy9")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KitchenTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KitchenTypeId");

                    b.ToTable("KitchenPrinters", (string)null);
                });

            modelBuilder.Entity("POS.Core.Entities.Kitchen.KitchenType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("KitchenName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("KitchenTypes", (string)null);
                });

            modelBuilder.Entity("POS.Core.Entities.Kitchen.PrintingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("ComputerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Copy1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Copy2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Copy3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Copy4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Copy5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KitchenId")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OutLetType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchID");

                    b.HasIndex("KitchenId");

                    b.ToTable("PrintingSettings", (string)null);
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.OrderItemComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderItemDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemDetailId");

                    b.ToTable("OrderItemComments");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.OrderItemsDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("DineInOrderId")
                        .HasColumnType("int");

                    b.Property<bool?>("Discount")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ItemNameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MenuSalesItemId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("TotalAfterDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVoidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VoidAmount")
                        .HasColumnType("int");

                    b.Property<string>("VoidBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoidByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoidReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VoidTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DineInOrderId");

                    b.HasIndex("MenuSalesItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersDetails");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.OrderSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AddServiceToItemPrice")
                        .HasColumnType("bit");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<bool?>("CanCloseWithoutPrint")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CaptainTipsAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClosingReceiptCount")
                        .HasColumnType("int");

                    b.Property<string>("ComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerReceiptCount")
                        .HasColumnType("int");

                    b.Property<bool?>("DeductCaptainTips")
                        .HasColumnType("bit");

                    b.Property<int?>("FullKitchenReceiptCount")
                        .HasColumnType("int");

                    b.Property<int?>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("OrderStatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeparateReceiptCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Service")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tips")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OrderSettings");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.OrderTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MachineName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ActionDateTime");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderTracks");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressNotice")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ApartmentNum")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("AssignTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BackTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CaptainTipsDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashierID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CashierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CentralOrderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosingTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerCount")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DeliveryCompany")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DeliveryCompanyInfoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DeliveryFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("DiscountByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DiscountTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DiscountedItems")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DispatchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("DriverName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FemaleCount")
                        .HasColumnType("int");

                    b.Property<string>("FloorNum")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal?>("FreeItems")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HomeNum")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("KitchenOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaleCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("OrderNotice")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderState")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("OrderType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("TakeAway");

                    b.Property<DateTime?>("PackingOutTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Cash");

                    b.Property<string>("Phone1")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("PrintCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Remain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReservationCustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservationCustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReservationPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReservationRemain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ScheduleDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Service")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ShiftID")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TableID")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TableState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TakeawayCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("TakeawayCustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TakeawayCustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TakerID")
                        .HasColumnType("int");

                    b.Property<string>("TakerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TitleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVoid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VoidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoidBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("VoidByName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("VoidCount")
                        .HasColumnType("int");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("VoidTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WaiterID")
                        .HasColumnType("int");

                    b.Property<string>("WaiterName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("WithoutDeliveryFees")
                        .HasColumnType("bit");

                    b.Property<bool?>("WithoutService")
                        .HasColumnType("bit");

                    b.Property<bool?>("WithoutTax")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ZoneBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ZoneID")
                        .HasColumnType("int");

                    b.Property<string>("ZoneName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryCompanyInfoId");

                    b.HasIndex("ShiftID");

                    b.HasIndex("TakeawayCustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.PosFeatureSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PosFeatureSettings");
                });

            modelBuilder.Entity("POS.Core.Entities.ReservationEntity.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("FemaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaleCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ReservationPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReservationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("[OrderId] IS NOT NULL");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("POS.Core.Entities.Shift.ShiftHandover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("EndShiftTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromCashierID")
                        .HasColumnType("int");

                    b.Property<string>("FromCashierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ShiftNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartShiftTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToCashierID")
                        .HasColumnType("int");

                    b.Property<string>("ToCashierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("WorkingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ShiftHandovers", (string)null);
                });

            modelBuilder.Entity("POS.Core.Entities.Categorie.Category", b =>
                {
                    b.HasOne("POS.Core.Entities.Company.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Core.Entities.Kitchen.KitchenType", "KitchenType")
                        .WithMany("Categories")
                        .HasForeignKey("KitchenTypeId");

                    b.Navigation("Branch");

                    b.Navigation("KitchenType");
                });

            modelBuilder.Entity("POS.Core.Entities.Company.Branch", b =>
                {
                    b.HasOne("POS.Core.Entities.Company.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.CustomerAddress", b =>
                {
                    b.HasOne("POS.Core.Entities.Company.Branch", "Branch")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Core.Entities.Delivery.DeliveryCustomerInfo", "DeliveryCustomer")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("DeliveryCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Core.Entities.Delivery.DeliveryZone", "DeliveryZone")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("DeliveryZoneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Branch");

                    b.Navigation("DeliveryCustomer");

                    b.Navigation("DeliveryZone");
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.DeliveryZone", b =>
                {
                    b.HasOne("POS.Core.Entities.Company.Branch", "Branch")
                        .WithMany("DeliveryZones")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("POS.Core.Entities.DineIn.Table", b =>
                {
                    b.HasOne("POS.Core.Entities.DineIn.TableGroup", "TableGroup")
                        .WithMany("Tables")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TableGroup");
                });

            modelBuilder.Entity("POS.Core.Entities.Item.AttributeItem", b =>
                {
                    b.HasOne("POS.Core.Entities.Item.Attributes", "Attribute")
                        .WithMany("AttributeItems")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Core.Entities.Item.MenuSalesItems", "RelatedMenuItem")
                        .WithMany()
                        .HasForeignKey("RelatedMenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("RelatedMenuItem");
                });

            modelBuilder.Entity("POS.Core.Entities.Item.MenuSalesItems", b =>
                {
                    b.HasOne("POS.Core.Entities.Item.Attributes", "Attribute")
                        .WithOne()
                        .HasForeignKey("POS.Core.Entities.Item.MenuSalesItems", "AttributeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POS.Core.Entities.Company.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POS.Core.Entities.Categorie.Category", "Category")
                        .WithMany("MenuSalesItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Core.Entities.Kitchen.KitchenType", "KitchenType")
                        .WithMany("Items")
                        .HasForeignKey("KitchenTypeId");

                    b.Navigation("Attribute");

                    b.Navigation("Branch");

                    b.Navigation("Category");

                    b.Navigation("KitchenType");
                });

            modelBuilder.Entity("POS.Core.Entities.Item.OrderItemAttributes", b =>
                {
                    b.HasOne("POS.Core.Entities.Item.AttributeItem", "AttributeItem")
                        .WithMany()
                        .HasForeignKey("AttributeItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POS.Core.Entities.OrderEntity.OrderItemsDetails", "OrderItem")
                        .WithMany("OrderItemAttributes")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeItem");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("POS.Core.Entities.Kitchen.KitchenPrinters", b =>
                {
                    b.HasOne("POS.Core.Entities.Kitchen.KitchenType", "KitchenType")
                        .WithMany("KitchenPrinters")
                        .HasForeignKey("KitchenTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KitchenType");
                });

            modelBuilder.Entity("POS.Core.Entities.Kitchen.PrintingSettings", b =>
                {
                    b.HasOne("POS.Core.Entities.Kitchen.KitchenType", "Kitchen")
                        .WithMany()
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.OrderItemComment", b =>
                {
                    b.HasOne("POS.Core.Entities.OrderEntity.OrderItemsDetails", "OrderItemDetail")
                        .WithMany("OrderItemComments")
                        .HasForeignKey("OrderItemDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItemDetail");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.OrderItemsDetails", b =>
                {
                    b.HasOne("POS.Core.Entities.DineIn.DineInOrder", "DineInOrder")
                        .WithMany("OrderDetails")
                        .HasForeignKey("DineInOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("POS.Core.Entities.Item.MenuSalesItems", "MenuSalesItem")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MenuSalesItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("POS.Core.Entities.OrderEntity.Orders", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DineInOrder");

                    b.Navigation("MenuSalesItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.Orders", b =>
                {
                    b.HasOne("POS.Core.Entities.Delivery.DeliveryCompanyInfo", null)
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryCompanyInfoId");

                    b.HasOne("POS.Core.Entities.Shift.ShiftHandover", "Shift")
                        .WithMany("Orders")
                        .HasForeignKey("ShiftID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("POS.Core.Entities.Customer.TakeawayCustomer", "TakeawayCustomer")
                        .WithMany("Orders")
                        .HasForeignKey("TakeawayCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Shift");

                    b.Navigation("TakeawayCustomer");
                });

            modelBuilder.Entity("POS.Core.Entities.ReservationEntity.Reservation", b =>
                {
                    b.HasOne("POS.Core.Entities.OrderEntity.Orders", "Order")
                        .WithOne("Reservation")
                        .HasForeignKey("POS.Core.Entities.ReservationEntity.Reservation", "OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POS.Core.Entities.DineIn.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("POS.Core.Entities.Categorie.Category", b =>
                {
                    b.Navigation("MenuSalesItems");
                });

            modelBuilder.Entity("POS.Core.Entities.Company.Branch", b =>
                {
                    b.Navigation("CustomerAddresses");

                    b.Navigation("DeliveryZones");
                });

            modelBuilder.Entity("POS.Core.Entities.Company.Company", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("POS.Core.Entities.Customer.TakeawayCustomer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.DeliveryCompanyInfo", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.DeliveryCustomerInfo", b =>
                {
                    b.Navigation("CustomerAddresses");
                });

            modelBuilder.Entity("POS.Core.Entities.Delivery.DeliveryZone", b =>
                {
                    b.Navigation("CustomerAddresses");
                });

            modelBuilder.Entity("POS.Core.Entities.DineIn.DineInOrder", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("POS.Core.Entities.DineIn.TableGroup", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("POS.Core.Entities.Item.Attributes", b =>
                {
                    b.Navigation("AttributeItems");
                });

            modelBuilder.Entity("POS.Core.Entities.Item.MenuSalesItems", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("POS.Core.Entities.Kitchen.KitchenType", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Items");

                    b.Navigation("KitchenPrinters");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.OrderItemsDetails", b =>
                {
                    b.Navigation("OrderItemAttributes");

                    b.Navigation("OrderItemComments");
                });

            modelBuilder.Entity("POS.Core.Entities.OrderEntity.Orders", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("POS.Core.Entities.Shift.ShiftHandover", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
