namespace POS.Core.Entities.Order;

public class Order
{
    public int BranchID { get; set; }
    public int HistoryID { get; set; } 
    public int OrderID { get; set; }
    public string BranchName { get; set; }
    public int? ShiftID { get; set; }
    public int? ShiftIDUnbroken { get; set; }
    public int? CashierID { get; set; }
    public string CashierName { get; set; }
    public DateTime? OrderDate { get; set; }
    public string OrderType { get; set; }
    public string OrderState { get; set; }
    public int? DeliveryCompanyID { get; set; }
    public string DeliveryCompanyName { get; set; }
    public bool? Follow { get; set; }
    public int? FollowTo { get; set; }
    public string RecipeType { get; set; }
    public int? TakerID { get; set; }
    public string TakerName { get; set; }
    public string TitleName { get; set; }
    public int? CustomerID { get; set; }
    public string CustomerName { get; set; }
    public string Phone1 { get; set; }
    public string Phone2 { get; set; }
    public string HomeNum { get; set; }
    public string StreetName { get; set; }
    public string FloorNum { get; set; }
    public string ApartmentNum { get; set; }
    public string AddressNotice { get; set; }
    public int? ZoneID { get; set; }
    public string ZoneName { get; set; }
    public decimal? ZoneBonus { get; set; }
    public string DispatchID { get; set; }
    public int? DriverID { get; set; }
    public string DriverName { get; set; }
    public DateTime? AssignTime { get; set; }
    public DateTime? BackTime { get; set; }
    public int? StationID { get; set; }
    public string StationName { get; set; }
    public int? TableID { get; set; }
    public string TableName { get; set; }
    public string TableState { get; set; }
    public string SubTableID { get; set; }
    public string SubTableName { get; set; }
    public int? CallerID { get; set; }
    public string CallerName { get; set; }
    public int? WaiterID { get; set; }
    public string WaiterName { get; set; }
    public int? RequestCount { get; set; }
    public decimal? OnTable { get; set; }
    public decimal? UnDispatch { get; set; }
    public decimal? Subtotal { get; set; }
    public decimal? Tax { get; set; }
    public decimal? Service { get; set; }
    public decimal? DeliveryFees { get; set; }
    public decimal? MinChargeRemain { get; set; }
    public decimal? Discount { get; set; }
    public decimal? DiscountedItems { get; set; }
    public decimal? FreeItems { get; set; }
    public decimal? TotalDiscount { get; set; }
    public decimal? CashPaid { get; set; }
    public decimal? VisaPaid { get; set; }
    public decimal? MastercardPaid { get; set; }
    public decimal? AmexPaid { get; set; }
    public decimal? DinersClubPaid { get; set; }
    public decimal? Outstanding { get; set; }
    public decimal? FractionAdjustment { get; set; }
    public decimal? GrandTotal { get; set; }
    public decimal? Tips { get; set; }
    public decimal? TotalReturn { get; set; } // Default to 0
    public decimal? Paid { get; set; }
    public decimal? Remain { get; set; }
    public decimal? ReservationPaid { get; set; }
    public decimal? ReservationRemain { get; set; }
    public DateTime? ScheduleDateTime { get; set; }
    public int? MinCharge { get; set; }
    public int? CustomerCount { get; set; }
    public decimal? TotalMinCharge { get; set; }
    public string DiscountType { get; set; }
    public decimal? DiscountPercentage { get; set; }
    public bool? GrowingDiscount { get; set; }
    public int? StaffID { get; set; }
    public string StaffName { get; set; }
    public int? FamousID { get; set; }
    public string FamousName { get; set; }
    public int? DiscountBy { get; set; }
    public string DiscountByName { get; set; }
    public DateTime? DiscountTime { get; set; }
    public string DiscountReason { get; set; }
    public bool? WithoutService { get; set; }
    public bool? WithoutTax { get; set; }
    public bool? WithoutDeliveryFees { get; set; }
    public string OrderNotice { get; set; }
    public decimal? VoidAmount { get; set; }
    public int? VoidBy { get; set; }
    public string VoidByName { get; set; }
    public DateTime? VoidTime { get; set; }
    public string VoidReason { get; set; }
    public int? VoidCount { get; set; }
    public decimal? TotalVoid { get; set; }
    public int? PrintCount { get; set; }
    public DateTime? KitchenOutTime { get; set; }
    public DateTime? PackingOutTime { get; set; }
    public DateTime? LastAddition { get; set; }
    public DateTime? ClosingTime { get; set; }
    public decimal? Cost { get; set; }
    public decimal? Profit { get; set; }
    public bool? DontMake { get; set; }
    public bool? Collected { get; set; }
    public int? CollectorID { get; set; }
    public string CollectorName { get; set; }
    public int? ItemCount { get; set; }
    public string Source { get; set; }
    public bool? Sent { get; set; }
    public DateTime? SentDate { get; set; }
    public int? DestinationBranchID { get; set; }
    public string DestinationBranchName { get; set; }
    public int? OriginalHistoryID { get; set; }
    public int? OriginalOrderID { get; set; }
    public bool? Received { get; set; }
    public int? ReceiverID { get; set; }
    public string ReceiverName { get; set; }
    public DateTime? ReceivedDate { get; set; }
    public string POSName { get; set; }
    public bool? Closed { get; set; }
    public bool? Updated { get; set; }
    public string Barcode { get; set; }
    public string OrderStamp { get; set; }
    public bool? HasComplaint { get; set; }
    public bool? Locked { get; set; }
    public bool? HandedOver { get; set; }
    public string SystemMessage { get; set; }
    public bool? Synchronized { get; set; } // Default to 0
}

